version: '3'

services:
  app:
    build: .
    container_name: fullcycle-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/fullcycle/app
    ports:
      - '8000:8000'
